# Introdução ao NumPy

In [1]:
import numpy as np

# Criando uma matriz unidimensional

In [2]:

matriz = np.array([1, 2, 3, 4, 5])
print(matriz)
print(type(matriz))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#
matriz_float = np.array([1, 2, 3], dtype=np.float64)
print(matriz_float)
print(type(matriz_float))

matriz_int = np.array([1, 2, 3], dtype=np.int32)
print(matriz_int)
print(type(matriz_int))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


# Mudando os Tipos do Array
# Podemos transformar tipo de dados de array

In [4]:

matriz_nova = np.array([1.4, 4.6, -7.6, 0.45, 4.99999])
print(matriz_nova)

# Se mudarr para int, vai truncar os valores
matriz_nova = matriz_nova.astype(np.int32)
print(matriz_nova)

[ 1.4      4.6     -7.6      0.45     4.99999]
[ 1  4 -7  0  4]


In [5]:
# Posso mudar
matriz_nova2 = np.array([1, 2, 3, 4])
print(matriz_nova2.astype(np.float64))


[1. 2. 3. 4.]


In [6]:
matriz_varias_lihas = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
print(matriz_varias_lihas)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Array vazio tipificados

In [7]:

matriz_vazia = np.empty([3,3], dtype=int)
print(matriz_vazia)
print('---------------')

# Array com valores Zero
zeros = np.zeros([3,3])
print(zeros)
print('---------------')

# Valores iguais a um
matriz_um = np.ones([5,5])
print(matriz_um)


[[    0     1     0]
 [  592  1264     0]
 [  768 32764     0]]
---------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Gerando Matriz Aleatórias

In [24]:

aleatorio = np.random.random((5))
print(aleatorio)

aleatorios_negativo = np.random.randn((5))
print(aleatorios_negativo)

aleatorio_10 = (10 * np.random.random(5))
aleatorio_10_truncado = ((10 * np.random.random(5)).astype(np.int32))
print(aleatorio_10)
print(aleatorio_10_truncado)

[0.01151303 0.71159122 0.89783605 0.544651   0.02366731]
[ 0.25510996 -0.87849041  1.45948063  1.02999645  0.26845779]
[4.79432305 9.02465334 7.7882525  8.09012068 0.50155974]
[9 2 7 9 5]


In [32]:
# Outra forma de gerar números aleatórios
gnr = np.random.default_rng(1)
aleatorio_5  = gnr.random(3)

print(aleatorio_5)

[0.51182162 0.9504637  0.14415961]


# Unique removendo repetições

In [49]:

j = np.array([[3, 6, 2, 8, 1, 4, 5, 7, 9, 10, 3, 2, 5, 30, 8, 1, 10, 4, 6, 7, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 5, 7, 2, 3, 9, 1, 6, 8, 4, 10,15]])
j = np.unique(j)

print(j)

[ 1  2  3  4  5  6  7  8  9 10 15 30]


In [39]:
# Criando Matriz Bidimensional

k = np.array([[1, 2, 3], [4, 5, 6]])
print(k)
print(k[0][2])
print(k.shape)

[[1 2 3]
 [4 5 6]]
3
(2, 3)


# Funções Matemáticas

In [51]:
array_matematica = np.array([3, 6, 2, 8, 1, 4, 5, 7, 9, 10, 3, 2, 5, 8, 1, 10, 4, 6, 7, 9])
print(array_matematica.max())
print(array_matematica.min())
print(array_matematica.sum())
print(array_matematica.mean())
# Desvio Padrão
print(array_matematica.std())

10
1
110
5.5
2.8722813232690143


# Funções universais aplicadas a todos elementos

In [54]:
k = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k))
print(np.exp(k))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


# Extrações de linhas e coluas

In [62]:
l = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(l)
print('----------------')

#Linhas
linhas_1 = l[0]
print(linhas_1)
print('----------------')
linhas_2 = l[1]
print(linhas_2)
print('----------------')
linhas_3 = l[2]
print(linhas_3)
print('----------------')

# Colunas
coluna_1 = l[:, 0]
print(coluna_1)
print('----------------')
coluna_2 = l[:, 1]
print(coluna_2)
print('----------------')
coluna_3 = l[:, 2]
print(coluna_3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------
[1 2 3]
----------------
[4 5 6]
----------------
[7 8 9]
----------------
[1 4 7]
----------------
[2 5 8]
----------------
[3 6 9]


# Adição de multiplicação de matrizes

In [71]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[1, 4], [7, 4]])
matriz3 = np.array([[2, 4], [3, 4]])

resultado = matriz1 + matriz2
print(resultado)
print(resultado * matriz3)

[[ 2  6]
 [10  8]]
[[ 4 24]
 [30 32]]


# Transposição,

In [73]:
f = np.arange(20).reshape(4, 5)
g = np.arange(20).reshape(10, 2)
print(f)
print(g)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
