# Introdução ao NumPy

In [1]:
import numpy as np

In [7]:
# Criando uma matriz unidimensional
matriz = np.array([1, 2, 3, 4, 5])
print(matriz)
print(type(matriz))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#
matriz_float = np.array([1, 2, 3], dtype=np.float64)
print(matriz_float)
print(type(matriz_float))

matriz_int = np.array([1, 2, 3], dtype=np.int32)
print(matriz_int)
print(type(matriz_int))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [12]:
# Mudando os Tipos do Array
# Podemos transformar tipo de dados de array
matriz_nova = np.array([1.4, 4.6, -7.6, 0.45, 4.99999])
print(matriz_nova)

# Se mudarr para int, vai truncar os valores
matriz_nova = matriz_nova.astype(np.int32)
print(matriz_nova)

[ 1.4      4.6     -7.6      0.45     4.99999]
[ 1  4 -7  0  4]


In [ ]:
# Posso mudar
matriz_nova2 = np.array([1, 2, 3, 4])
print(matriz_nova2)
